version: "3.9"

volumes:
  postgres-data:
  mariadb-data:
  seafile-data:

secrets:
  db_user:
    file: secrets/db_user
  db_pass:
    file: secrets/db_pass

networks:
  seafile-net:

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  nginx:
    build: ./nginx
    environment:
      - VIRTUAL_HOST=app.localhost
    expose:
      - 80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

        #  postgres:
        #    image: postgres
        #    env_file:
        #      - ./postgres/environment
        #    ports:
        #      - "5432:5432"
        #    secrets:
        #      - db_user
        #      - db_pass
        #    volumes:
        #      - postgres-data:/var/lib/postgres/data/
        #      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        #    restart: always

  mariadb:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pass
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - seafile-net
    secrets:
      - db_user
      - db_pass

  seafile-server:
    image: ggogel/seafile-server:8.0.3
    volumes:
      - seafile-data:/shared 
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=flafgiraf
      - HEST=/run/secrets/db_pass
      - TIME_ZONE=Europe/Copenhagen
      - HTTPS=false # Set this to true if you plan to use a reverse proxy with HTTPS. Can be changed later in the admin settings on the web-ui.
      - SEAFILE_SERVER_HOSTNAME=seafile.mydomain.com # Mandatory on first deployment!
    depends_on:
      - mariadb
        #- memcached
        #- seafile-caddy
    networks:
      - seafile-net 
    secrets:
      - db_user
      - db_pass

  seafile-hub:
    image: ggogel/seahub:8.0.3
    volumes:
      - seafile-data:/shared
        #- seahub-avatars:/shared/seafile/seahub-data/avatars
        #- seahub-custom:/shared/seafile/seahub-data/custom
    environment:
      - SEAFILE_ADMIN_EMAIL=allannk@gmail.com
      - SEAFILE_ADMIN_PASSWORD=flafgiraf
    depends_on:
      - seafile-server
        #- seafile-caddy
    networks:
      - seafile-net

