FROM nextcloud:fpm-alpine

# -------------------------
# Change nextcloud group ID
#RUN sed -i 's/www-data:x:[0-9]*:.*$/www-data:x:1000:www-data/g' /etc/group
#RUN sed -i 

# Chown nextcloud data files
#RUN chown www-data:www-data /var/www/html -R

#RUN groupmod -g 1000 users && \
#    usermod -g 1000 www-data && \
#    chown www-data:users /var/www/ -R
